main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
]

menu/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = "menu"

urlpatterns = [
    path('', views.index, name="index"),
    path('info/<int:pizza_id>/', views.pizza_info, name="info"),
]

pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models


# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0)
    vegetarian = models.BooleanField(default=False)
    image = models.ImageField(upload_to="images", null=True, blank=True)

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    # return HttpResponse("Your main page")
    return render(request, "main/index.html")

menu/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Pizza


# Create your views here.

# /menu
def index(request):
    """pizzas = Pizza.objects.all()
    pizzas_names_price = [f"<b>{pizza.name} : {pizza.price} руб.</b> <br>" for pizza in pizzas]
    pizzas_names_str = "".join(pizzas_names_price)
    return HttpResponse(pizzas_names_str)"""
    pizzas = Pizza.objects.all().order_by("price")
    return render(request, "menu/index.html", {"Пицца": pizzas})


def pizza_info(request, pizza_id):
    pizza = get_object_or_404(Pizza, id=pizza_id)
    return render(request, "menu/pizza_info.html", {"pizza": pizza})

main/templates/main/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
    <div class="centered">
        <img src="{% static 'main/images/main_logo.png' %}"/>
        <a href="{% url 'menu:index' %}">Просмотреть меню</a>
    </div>
</body>
</html>

menu/templates/menu/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Наше меню</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
    <a href="{% url 'main:index' %}">
        <img id="small_logo" src="{% static 'menu/images/small_logo.png' %}" alt="Логтип">
    </a>
    <div class="name"><h1>Меню</h1></div>
    <div class="menu_list">
        {% for pizza in Пицца %}
            <div class="menu_list_item">
                <a class="pizza_name" href="{% url 'menu:info' pizza.id %}" style="text-decoration:none; color: white"> <span class="menu_list_title" > {{pizza.name}}:</span></a>
                <span class="menu_list_price">{{pizza.price | floatformat:2}} руб.</span>
                <br>
                <div>
                {% if pizza.vegetarian %}
                    <span class="menu_list_badge">Вегетарианская</span>
                {% endif %}
                </div>
                <span class="menu_list_ingredients">{{pizza.ingredients}}</span>
            </div>
        {% endfor %}
    </div>
</body>
</html>

menu/templates/menu/pizza_info.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{pizza.name}}</title>
    <link rel="stylesheet" href="{% static 'menu/info_style.css' %}">
</head>
<body>
    <h1 class="title"></h1>
    <div class="content">
        <h1>{{pizza.name}}</h1>
        <img src="{{pizza.image.url}}" height="300">
        <p>{{pizza.ingredients}}</p>
    </div>
</body>
</html>